apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: kirigwidev/client:latest
          ports:
            - containerPort: 3000  # Change this from 80 to 3000
          env:
            - name: NEXT_PUBLIC_BASE_URL
              value: "http://client-service:3000"  # Change this from 80 to 3000
            - name: BACKEND_API_URL
              value: "http://server-service:8080/kyosk/api/v1/books"