apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000  # Change this from 80 to 3000
      targetPort: 3000  # Change this from 80 to 3000
  type: NodePort